#!/usr/bin/env bash
# This script displays the username, user id, and home directory from /etc/passwd
while IFS=':' read -r username password uid gid geocos home shell
do
    echo "$username:$uid:$home"
done < /etc/passwd
