#!/usr/bin/env bash
# This script parses /etc/passwd and prints a story for each user
while IFS=':' read -r username password uid gid geocos home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $geocos"
done < /etc/passwd
