#!/usr/bin/env bash
# This script groups Apache log visitors by IP and HTTP status code, ordered by occurrence
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
