#!/usr/bin/env bash
# This script displays the content of the current directory showing only parts after the first dash
for file in *
do
    if [ -f "$file" ] || [ -d "$file" ]
    then
        echo "$file" | cut -d'-' -f2-
    fi
done
