#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with a 2-second sleep interval
# Traps SIGTERM and outputs "I am invincible!!!" when received

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
